# Set TEST_BUILDS=1 to run library_builders tests

language: generic

matrix:
  include:
    - os: linux
      dist: precise
      env:
        - TEST_BUILDS=1

script:
  - source tests/test_multibuild.sh
